</body>
<!--<footer>-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">-->
<!--                <ul class="list-inline text-center">-->
<!--                    <li>-->
<!--                        <a href="#">-->
<!--                                <span class="fa-stack fa-lg">-->
<!--                                    <i class="fa fa-circle fa-stack-2x"></i>-->
<!--                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>-->
<!--                                </span>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="#">-->
<!--                                <span class="fa-stack fa-lg">-->
<!--                                    <i class="fa fa-circle fa-stack-2x"></i>-->
<!--                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>-->
<!--                                </span>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="#">-->
<!--                                <span class="fa-stack fa-lg">-->
<!--                                    <i class="fa fa-circle fa-stack-2x"></i>-->
<!--                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>-->
<!--                                </span>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--                <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</footer>-->
<!--<div id="footer" class="container">-->
<!--    <nav class="navbar navbar-default navbar-fixed-bottom">-->
<!--        <div class="navbar-inner navbar-content-center">-->
<!--            <p class="text-muted credit">© Copyright</p>-->
<!--        </div>-->
<!--    </nav>-->
<!--</div>-->
<footer class="footer">
    <div class="large-12 columns">
        <div class="row">
            <div class="large-6 columns">
                <p>© Copyright</p>
            </div>
            <div class="large-6 columns">
                <ul class="inline-list right">
                    <li><a href="#">Link 1</a></li>
                    <li><a href="#">Link 2</a></li>
                    <li><a href="#">Link 3</a></li>
                    <li><a href="#">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
