</body>
<div id="footer" class="container">
    <nav class="navbar navbar-default navbar-fixed-bottom">
        <div class="navbar-inner navbar-content-center">
            <p class="text-muted credit">© Copyright</p>
        </div>
    </nav>
</div>
<!--<footer class="footer">-->
<!--    <div class="large-12 columns">-->
<!--        <div class="row">-->
<!--            <div class="large-6 columns">-->
<!--                <p>© Copyright</p>-->
<!--            </div>-->
<!--            <div class="large-6 columns">-->
<!--                <ul class="inline-list right">-->
<!--                    <li><a href="#">Link 1</a></li>-->
<!--                    <li><a href="#">Link 2</a></li>-->
<!--                    <li><a href="#">Link 3</a></li>-->
<!--                    <li><a href="#">Link 4</a></li>-->
<!--                </ul>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</footer>-->
