<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $this->getTitle(); ?></title>
    <link rel="stylesheet" href="<?php echo $this->addAsset('css/bootstrap.css')?>">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="<?php echo $this->addAsset('js/bootstrap.js')?>"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href=<?php echo Bootstrap::getUrl('/blog/view/list')?>>My Blog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar">
                    <li><a href=<?php echo Bootstrap::getUrl('/blog/page/about')?>>About</a></li>
                    <li><a href=<?php echo Bootstrap::getUrl('/blog/page/contact')?>>Contact</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=<?php echo Bootstrap::getUrl('/base/account/logout')?>>Log out</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>




