<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $this->getTitle(); ?></title>
    <link rel="stylesheet" href="<?php echo $this->addAsset('css/bootstrap.css')?>">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="<?php echo $this->addAsset('js/bootstrap.js')?>"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand">My Blog</a>
        </div>
    </div>
</nav>
