<form id="registration" method="POST" action="cms/account/register">
    <label for="firstname">First Name</label><em>*</em>
    <input id="firstname" type="text" name="name" class="required"/></br>
    <label for="lastname">Last Name</label><em>*</em>
    <input id="lastname" type="text" name="name" class="required"/></br>
    <label for="email">Email</label><em>*</em>
    <input id="email" type="email" name="email" class="required"/></br>
    <label for="password">Password</label><em>*</em>
    <input id="password" type="password" name="password" class="required"/></br>
    <input id="is-active" type="hidden" name="is-active" value="1" />
    <button type="button" class="register-button">Register</button>
</form>
