<h2>Admin Login</h2>
<form id="login" method="POST" action="/base/account/login">
    <label for="email">Email</label><em>*</em>
    <input id="email" type="email" name="email" class="required"/></br>
    <label for="password">Password</label><em>*</em>
    <input id="password" type="password" name="password" class="required"/></br>
    <input id="is-active" type="hidden" name="is-active" value="1" />
    <button type="submit" class="login-button">Login</button>
</form>

