<form id="registration" method="POST" action="cms/account/register">
    <div class="row">
        <label for="name">Name</label><em>*</em>
        <input id="name" type="text" name="name" class="required"/></br>
    </div>
    <div class="row">
        <label for="email">Email</label><em>*</em>
        <input id="email" type="email" name="email" class="required"/></br>
    </div>
    <div class="row">
        <label for="password">Password</label><em>*</em>
        <input id="password" type="password" name="password" class="required"/></br>
    </div>
    <input id="is-active" type="hidden" name="is-active" value="1" />
    <button type="button" class="register-button">Register</button>
</form>
