<div>
    <form id="update_post_form" method="POST" action="<?php echo Bootstrap::getUrl('/admin/admin/post'); ?>">
        <div class="row">
            <label for="title">Title</label><em>*</em><br/>
            <input id="title" class="input" name="title" type="text" size="100"
             value="<?php echo $this->_data['title']?>"/><br/>
        </div>
        <div class="row">
            <label for="image">Image</label><br/>
            <input id="image" class="input" name="image" type="text" size="100"
             value="<?php echo $this->_data['image']?>"/><br/>
        </div>
        <div class="row">
            <label for="content">Content</label><em>*</em><br/>
            <textarea id="content" class="input" name="content" rows="50" cols="100"
             value="<?php echo $this->_data['content']?>"></textarea><br/>
        </div>
        <div>
            <input id="is-active" type="hidden" name="is-active" value="1" />
            <button class="update-button">Update</button>
        </div>
    </form>
</div>