<form>
    <hr/>
    <div class="row">
        <label for="name">Name</label><em>*</em><br />
        <input id="name" class="input" name="name" type="text" size="20" /><br />
    </div>
    <div class="row">
        <label for="comment">Comment</label><em>*</em><br />
        <textarea id="comment" class="input" name="comment" rows="10" cols="100"></textarea><br />
    </div>
    <input id="is-active" type="hidden" name="is-active" value="1" />
    <button type="button" class="submit-button">Submit</button>
</form>