<!--<div class="container">-->
<!--    <div class="col-md-4 col-md-offset-2">-->
<!--        <form id="login" method="POST" action="/base/account/login">-->
<!--            <label for="email">Email</label><em>*</em>-->
<!--            <input id="email" type="email" name="email" value="--><?php //echo htmlentities('') ?><!--"/></br>-->
<!--            <label for="password">Password</label><em>*</em>-->
<!--            <input id="password" type="password" name="password" class="required"/></br>-->
<!--            <input id="is-active" type="hidden" name="is-active" value="1" />-->
<!--            <button type="submit" class="login-button">Login</button>-->
<!--        </form>-->
<!--    </div>-->
<!--</div>-->

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading"> <strong class="">Login</strong>
                </div>
                <div class="panel-body">
                    <form id="login" class="form-horizontal" method="POST" action="/base/account/login">
                        <div class="form-group">
<!--                            <label for="email" class="col-sm-2 control-label">Email</label>-->
                            <div class="col-sm-8 col-sm-offset-2">
                                <input type="email" class="form-control" id="email" placeholder="Email" name="email">
                            </div>
                        </div>
                        <div class="form-group">
<!--                            <label for="password" class="col-sm-2 control-label">Password</label>-->
                            <div class="col-sm-8 col-sm-offset-2">
                                <input type="password" class="form-control" id="password" placeholder="Password" name="password">
                            </div>
                        </div>
                        <div class="form-group last">
                            <div class="col-sm-8 col-sm-offset-2">
                                <button type="submit" class="btn btn-success btn-block">Sign in</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">Not registered? <a href="<?php echo Bootstrap::getUrl('/base/account/register')?>" class="">Register here</a>
                </div>
            </div>
        </div>
    </div>
</div>