<div id="wrap">
    <div class="container">
        <h1>Admin Panel</h1>
        <p>Hello, <?php echo Core_Session::getSessionVariable('admin', 'admin-logged-in')?>!</p>
        <div class="#">
            <input id="is-active" type="hidden" name="is-active" value="1" />
            <button type="submit" class="btn btn-primary">Create Post</button>
        </div>
        <div>
            <h3>Blog Posts</h3>
            <div>
                <?php foreach($this->_data as $posts):?>
                    <?php foreach($posts as $post): ?>
                <h4><?php echo $post['title']?></h4>
                <p><?php echo $post['content']?></p>
                <div>
                    <a href="<?php echo BASE_URL . '/admin/admin/update?id='?>"
                       class="btn btn-warning" role="'button">Edit Post</a>
                </div>
                <div>
                    <a href="<?php echo BASE_URL . '/admin/admin/delete?id='?>"
                       class="btn btn-danger" role="'button">Delete Post</a>
                </div>
                <?php endforeach ?>
                <?php endforeach ?>
            </div>
        </div>
    </div>
</div>

