<div class="container-fluid">
    <div>
        <div class="container col-md-2">
            <div>
                <h1>Hello, </h1>
                <h3><?php echo Core_Session::getSessionVariable('admin', 'logged-in')?>!</h3>
            </div>
            <div>
                <h4>Welcome to the admin panel.</h4>
            </div>
            <div>
                <a href="<?php echo Bootstrap::getUrl('/admin/admin/create/')?>"
                  class="btn btn-primary btn-lg btn-block" role="button">Create Post</a>
            </div>
        </div>
        <div class="container col-md-8 col-md-offset-1">
            <div class="row">
                <div class="col-md-4">
                    <h1>Blog Posts</h1>
                </div>
            </div>
            <div class="row">
                <?php foreach($this->_posts as $post):?>
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel panel-heading">
                            <div>
                                <div class="pull-right">
                                    <a href="<?php echo Bootstrap::getUrl('/admin/admin/delete/?id=') . $post['id']?>"
                                       class="btn btn-danger" role="button">Delete Post</a>
                                    <a href="<?php echo Bootstrap::getUrl('/admin/admin/update/?id=' . $post['id'])?>"
                                       class="btn btn-warning" role="button">Edit Post</a>
                                    <a href="<?php echo Bootstrap::getUrl('/blog/page/view/id/' . $post['id'])?>"
                                       class="btn btn-success" role="button">Read Post</a>
                                </div>
                                <h3><?php echo $post['title']?></h3>
                                <h6>Posted by <?php echo $post['author']?> on <?php echo $post['date']?></h6>
                            </div>
                        </div>
                        <div class="panel panel-body">
                            <p><?php echo $post['content']?></p>
                        </div>
                    </div>
                </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
</div>

