<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <?php echo $this->addBlock('title'); ?>
    <link rel="stylesheet" href="<?php echo $this->addAsset('css')?>">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="<?php echo $this->addAsset('js')?>"></script>
</head>
<body>
<form id="contact_form" method="POST"  action="cms/admin/index">
    <div class="row">
        <label for="title">Title:</label><br />
        <input id="title" class="input" name="title" type="text" value="" size="100" /><br />
    </div>
    <div class="row">
        <label for="image">Image:</label><br />
        <input id="image" class="input" name="image" type="text" value="" size="100" /><br />
    </div>
    <div class="row">
        <label for="content">Content:</label><br />
        <textarea id="content" class="input" name="content" rows="50" cols="100"></textarea><br />
    </div>
    <input id="is-active" type="hidden" name="is-active" value="1" />
    <button type="button" class="post-button">Post</button>
</form>
</body>
</html>