<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <?php echo $this->addBlock('title'); ?>
    <link rel="stylesheet" href="<?php echo $this->addAsset('css')?>">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="<?php echo $this->addAsset('js/clickimage.js')?>"></script>
</head>
<body>
<div class="row">
    <div class="large-12 columns">
        <div class="nav-bar right">
            <ul class="button-group">
                <li><a href="http://application.dev/cms/account/admin" class="button">Create Post</a></li>
                <li><a href="#" class="button">Link 2</a></li>
                <li><a href="#" class="button">Link 3</a></li>
                <li><a href="#" class="button">Link 4</a></li>
            </ul>
        </div>
        <img src="<?php echo $this->addAsset('image/blueacorn.jpg')?>"/>
        <h1>Blog Title</h1>
        <hr/>
    </div>
</div>






<div class="row">


    <div class="large-9 columns" role="content">

        <article>

            <h3><a href="#">Blog Post Title</a></h3>
            <h6>Written by <a href="#">John Smith</a> on August 12, 2012.</h6>

            <div class="row">
                <div class="large-6 columns">
                    <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa.</p>
                    <p>Boudin aliqua adipisicing rump corned beef. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
                </div>
                <div class="large-6 columns">
                    <img src="http://placehold.it/400x240&text=[img]"/>
                </div>
            </div>

            <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>

            <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>

        </article>

        <form>
            <hr/>
            <div class="row">
                <label for="name">Name</label><em>*</em><br />
                <input id="name" class="input" name="name" type="text" size="20" /><br />
            </div>
            <div class="row">
                <label for="comment">Comment</label><em>*</em><br />
                <textarea id="comment" class="input" name="comment" rows="10" cols="100"></textarea><br />
            </div>
            <input id="is-active" type="hidden" name="is-active" value="1" />
            <button type="button" class="submit-button">Submit</button>
        </form>



<!--        <article>-->
<!---->
<!--            <h3><a href="#">Blog Post Title</a></h3>-->
<!--            <h6>Written by <a href="#">John Smith</a> on August 12, 2012.</h6>-->
<!---->
<!--            <div class="row">-->
<!--                <div class="large-6 columns">-->
<!--                    <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa.</p>-->
<!--                    <p>Boudin aliqua adipisicing rump corned beef. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>-->
<!--                </div>-->
<!--                <div class="large-6 columns">-->
<!--                    <img src="http://placehold.it/400x240&text=[img]"/>-->
<!--                </div>-->
<!--            </div>-->
<!---->
<!--            <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>-->
<!---->
<!--            <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>-->
<!---->
<!--        </article>-->
<!---->
<!--    </div>-->
<!---->
<!---->
<!---->
<!---->
<!---->
<!---->
<!--    <aside class="large-3 columns">-->
<!---->
<!--        <h5>Categories</h5>-->
<!--        <ul class="side-nav">-->
<!--            <li><a href="#">News</a></li>-->
<!--            <li><a href="#">Code</a></li>-->
<!--            <li><a href="#">Design</a></li>-->
<!--            <li><a href="#">Fun</a></li>-->
<!--            <li><a href="#">Weasels</a></li>-->
<!--        </ul>-->
<!---->
<!--        <div class="panel">-->
<!--            <h5>Featured</h5>-->
<!--            <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.</p>-->
<!--            <a href="#">Read More →</a>-->
<!--        </div>-->
<!---->
<!--    </aside>-->
<!---->
<!---->
<!--</div>-->






<footer class="row">
    <div class="large-12 columns">
        <hr/>
        <div class="row">
            <div class="large-6 columns">
                <p>© Copyright</p>
            </div>
            <div class="large-6 columns">
                <ul class="inline-list right">
                    <li><a href="#">Link 1</a></li>
                    <li><a href="#">Link 2</a></li>
                    <li><a href="#">Link 3</a></li>
                    <li><a href="#">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>


</body>
</html>