<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <?php $this->addBlock('cms/title'); ?>
    <link rel="stylesheet" href="<?php echo $this->addAsset('css/ugly')?>">
    <script src="<?php echo $this->addAsset('js')?>"></script>
</head>
<body>
<?php $this->addBlock('cms/header') ?>
<?php $this->addBlock('cms/content') ?>
<img src="<?php echo $this->addAsset('images/blueacorn.jpg')?>"/>
<?php $this->addBlock('cms/footer') ?>
</body>
</html>