<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <?php echo $this->addBlock('title'); ?>
    <link rel="stylesheet" href="<?php echo $this->addAsset('css/sample.css')?>">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="<?php echo $this->addAsset('js/clickimage.js')?>"></script>
</head>
<body>
<?php echo $this->addBlock('blog_header') ?>
<?php echo $this->addBlock('entry') ?>
<img src="<?php echo $this->addAsset('image/blueacorn.jpg')?>"/>
<?php echo $this->addBlock('copyright') ?>
</body>
</html>