<?php $page = $this->getPage();?>
<?php $totalPages = $this->getTotalPages();?>
<div class="container-fluid">

    <div class="container">

        <div class="col-md-4 pull-right">

            <!-- Blog Search Well -->
            <div class="well">
                <h4>Looking for something?</h4>
                <div class="input-group">
                    <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Search</button>
                        </span>
                </div>
            </div>
        </div>

        <!-- Blog Post Content Column -->
        <div class="col-md-7">
            <div class="row">
                <?php foreach($page as $post):?>
                    <?php Core_Session::setSessionVariable('postsArray', $this->_posts)?>
                    <div class="row">
                        <div class="panel panel-default">
                            <div class="panel panel-heading">
                                <div>
                                    <div class="pull-right">
                                        <a href="<?php echo Bootstrap::getUrl('/blog/page/view/id/' . $post['id'])?>"
                                           class="btn btn-primary" role="button">View Post</a>
                                    </div>
                                    <h3><?php echo $post['title']?></h3>
                                    <h6>Posted by <?php echo $post['author']?> on <?php echo $post['date']?></h6>
                                </div>
                            </div>
                            <div class="panel panel-body">
                                <p><?php echo $post['content']?></p>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-8">
                    <ul class="pagination">
                        <li><a href="#">&laquo;</a></li>
                        <?php for($i = 1; $i <= $totalPages; $i++):?>
                            <?php if()?>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <?php endfor ?>
                        <li><a href="#">&raquo;</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
