<?php $array = Core_Session::getSessionVariable('postsArray') ?: array(); ?>
<?php $id = $this->_id ?>
<?php $post = array_key_exists($id, $array) ? $array[$id] : false ?>
<!-- Page Content -->
<div class="container">

    <div class="row">

        <!-- Blog Post Content Column -->
        <div class="col-lg-8">

            <!-- Blog Post -->

            <!-- Title -->
            <h1><?php echo $post['title']?></h1>

            <!-- Author -->
<!--            <p class="lead">-->
<!--                by <a href="#">Start Bootstrap</a>-->
<!--            </p>-->

            <hr>

            <!-- Date/Time -->
            <p>Posted by <?php echo $post['author']?> on <?php echo $post['date']?></p>

            <hr>

            <!-- Preview Image -->
            <img class="img-responsive" src="http://placehold.it/900x300" alt="">

            <hr>

            <!-- Post Content -->
            <p><?php echo $post['content']?></p>

            <hr>

            <!-- Blog Comments -->

            <!-- Comments Form -->
            <div class="well">
                <h4>Leave a Comment:</h4>
                <span style="color: red" id="titleError" class="col-md-5"><?php if(array_key_exists('comment', $errors)){ echo $errors['title']; }?></span>
                <form role="form">
                    <div class="form-group">
                        <textarea class="form-control" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>

            <hr>

            <!-- Posted Comments -->

            <!-- Comment -->
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">Start Bootstrap
                        <small>August 25, 2014 at 9:30 PM</small>
                    </h4>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
            </div>

            <!-- Comment -->
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">Start Bootstrap
                        <small>August 25, 2014 at 9:30 PM</small>
                    </h4>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
            </div>

        </div>

        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">
<!---->
            <!-- Blog Search Well -->
            <div class="well">
                <h4>Looking for something?</h4>
                <div class="input-group">
                    <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Search</button>
                        </span>
                </div>
                <!-- /.input-group -->
            </div>
<!---->
            <!-- Blog Categories Well -->
<!--            <div class="well">-->
<!--                <h4>Recent Posts</h4>-->
<!--                <div class="row">-->
<!--                    <div class="col-lg-6">-->
<!--                        <ul class="list-unstyled">-->
<!--                            <li><a href="#">Category Name</a>-->
<!--                            </li>-->
<!--                            <li><a href="#">Category Name</a>-->
<!--                            </li>-->
<!--                            <li><a href="#">Category Name</a>-->
<!--                            </li>-->
<!--                            <li><a href="#">Category Name</a>-->
<!--                            </li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                    <div class="col-lg-6">-->
<!--                        <ul class="list-unstyled">-->
<!--                            <li><a href="#">Category Name</a>-->
<!--                            </li>-->
<!--                            <li><a href="#">Category Name</a>-->
<!--                            </li>-->
<!--                            <li><a href="#">Category Name</a>-->
<!--                            </li>-->
<!--                            <li><a href="#">Category Name</a>-->
<!--                            </li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
                <!-- /.row -->
<!--            </div>-->
<!---->
            <!-- Side Widget Well -->
<!--            <div class="well">-->
<!--                <h4>Side Widget Well</h4>-->
<!--                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>-->
<!--            </div>-->
<!---->
<!--        </div>-->

    </div>